data_dir: 
  "../reroot_pipeline/viral_usher_trees/trees/"
database:
  "./ncbi_viral_blast/viral_taxid_db"
viruses:
  - Adeno_associated_virus_1
  - adeno_associated_virus_2
  - Adeno_associated_virus_3
  - Adeno_associated_virus_4
  - Adeno_associated_virus_7
  - Adeno_associated_virus_8
  - African_swine_fever_virus_26544_OG10
  - African_swine_fever_virus_47_Ss_2008
  - African_swine_fever_virus_ASFV_Georgia_2007_1
  - African_swine_fever_virus_BA71
  - African_swine_fever_virus_BA71V
  - African_swine_fever_virus_Benin_97_1
  - African_swine_fever_virus_E75
  - African_swine_fever_virus_Ken05_Tk1
  - African_swine_fever_virus_Ken06_Bus
  - African_swine_fever_virus_Kenya_1950
  - African_swine_fever_virus_L60
  - African_swine_fever_virus_Malawi_Lil_20_1_1983
  - African_swine_fever_virus_Mkuzi_1979
  - African_swine_fever_virus_NHV
  - African_swine_fever_virus_Odintsovo_02_14
  - African_swine_fever_virus_OURT_88_3
  - African_swine_fever_virus_Pretorisuskop_96_4
  - African_swine_fever_virus_Tengani_62
  - African_swine_fever_virus_Warmbaths
  - African_swine_fever_virus_Warthog
  - Aleutian_mink_disease_virus
  - Avian_leukemia_virus
  - Avian_leukosis_virus_RSA
  - Avian_orthoavulavirus_1_chicken_N_Ireland_Ulster_67
  - Avian_orthoavulavirus_1_JSD0812
  - Avian_orthoreovirus_AVS_B_L1
  - Avian_orthoreovirus_AVS_B_L2
  - Avian_orthoreovirus_AVS_B_L3
  - Avian_orthoreovirus_AVS_B_M1
  - Avian_orthoreovirus_AVS_B_M2
  - Avian_orthoreovirus_AVS_B_M3
  - Avian_orthoreovirus_AVS_B_S2
  - Avian_orthoreovirus_AVS_B_S3
  - Avian_orthoreovirus_AVS_B_S4
  - Beak_and_feather_disease_virus
  - Betacoronavirus_England_1
  - Betapolyomavirus_hominis
  - Bluetongue_virus_1
  - Bluetongue_virus_10
  - Bluetongue_virus_3
  - Bluetongue_virus_4
  - Bluetongue_virus_5
  - Bluetongue_virus_6
  - Bluetongue_virus_7
  - Bluetongue_virus_8
  - Bluetongue_virus_9
  - Bocaparvovirus_primate1_Salvador1
  - Bocaparvovirus_primate1_st2
  - Bocavirus_gorilla_GBoV1_2009
  - Bovine_leukemia_virus
  - bovine_respiratory_syncytial_virus
  - Bovine_respiratory_syncytial_virus_ATCC51908
  - Bovine_viral_diarrhea_virus_1
  - Bovine_viral_diarrhea_virus_1_SD1
  - Camel_alphacoronavirus
  - canine_distemper_virus
  - Canine_parvovirus
  - Capillovirus_mali
  - Cardamom_bushy_dwarf_virus_DNA_U3
  - Cardamom_bushy_dwarf_virus_M
  - Cardamom_bushy_dwarf_virus_NC_038808_1
  - Cardamom_bushy_dwarf_virus_NC_038809_1
  - Cardamom_bushy_dwarf_virus_NC_038810_1
  - Cardamom_bushy_dwarf_virus_NC_038816_1
  - Chicken_anemia_virus
  - Chikungunya_virus
  - Chimpanzee_adenovirus_Y25
  - Citrus_tristeza_virus
  - Classical_swine_fever_virus
  - Classical_swine_fever_virus_Alfort_187
  - Columbid_circovirus
  - Coxsackievirus_A2
  - Coxsackievirus_B3
  - Deformed_wing_virus
  - dengue_virus_type_1
  - dengue_virus_type_2
  - dengue_virus_type_3
  - dengue_virus_type_4
  - Duck_coronavirus
  - Eastern_equine_encephalitis_virus
  - Enterovirus_A
  - enterovirus_A114
  - Enterovirus_B
  - Enterovirus_C
  - enterovirus_D68
  - Epizootic_hemorrhagic_disease_virus_serotype_1_strain_New_Jersey_1
  - Epizootic_hemorrhagic_disease_virus_serotype_1_strain_New_Jersey_3
  - Epizootic_hemorrhagic_disease_virus_serotype_1_strain_New_Jersey_4
  - Epizootic_hemorrhagic_disease_virus_serotype_1_strain_New_Jersey_5
  - Epizootic_hemorrhagic_disease_virus_serotype_1_strain_New_Jersey_7
  - Epizootic_hemorrhagic_disease_virus_serotype_1_strain_New_Jersey_9
  - Equid_alphaherpesvirus_1
  - Equine_arteritis_virus
  - Feline_calicivirus_NC_075569_1
  - Feline_calicivirus_Urbana
  - Feline_infectious_peritonitis_virus
  - Foot_and_mouth_disease_virus_O
  - Foveavirus_mali
  - Gallid_alphaherpesvirus_1_Composite_of_6_strains
  - Gallid_alphaherpesvirus_1_SA2
  - Gallid_alphaherpesvirus_2
  - GB_virus_C
  - Grapevine_leafroll_associated_virus_3
  - Grapevine_Pinot_gris_virus
  - Grapevine_rupestris_stem_pitting_associated_virus
  - Hepatitis_B_virus
  - Hepatitis_C_virus_genotype_1
  - Hepatitis_C_virus_genotype_2
  - Hepatitis_C_virus_genotype_3
  - Hepatitis_C_virus_genotype_4
  - Hepatitis_C_virus_genotype_6
  - Hepatitis_C_virus_isolate_H77
  - Hepatitis_delta_virus_dFr2005
  - Hepatitis_delta_virus_dFr2072
  - Hepatitis_delta_virus_dFr2158
  - Hepatitis_delta_virus_NC_001653_2
  - Hepatitis_delta_virus_NC_076110_1
  - hepatitis_D_virus_1
  - Hepatitis_E_virus
  - Hepatovirus_A
  - Hop_stunt_viroid
  - Horsepox_virus
  - Human_adenovirus_1
  - Human_adenovirus_2
  - Human_adenovirus_35
  - Human_adenovirus_5
  - Human_adenovirus_54
  - Human_adenovirus_7
  - Human_alphaherpesvirus_1
  - Human_alphaherpesvirus_2
  - Human_alphaherpesvirus_3
  - Human_betaherpesvirus_5
  - Human_bocavirus_3
  - Human_coronavirus_229E
  - Human_coronavirus_NL63
  - Human_coronavirus_OC43
  - Human_gammaherpesvirus_4
  - Human_gammaherpesvirus_8
  - Human_herpesvirus_4_type_2
  - Human_immunodeficiency_virus_1
  - Human_immunodeficiency_virus_2
  - Human_mastadenovirus_B_Human_adenovirus_11
  - Human_mastadenovirus_B_Human_adenovirus_3
  - Human_mastadenovirus_C
  - Human_mastadenovirus_D_Human_adenovirus_type_17
  - Human_mastadenovirus_E
  - Human_mastadenovirus_F
  - Human_metapneumovirus
  - Human_orthopneumovirus_B1
  - Human_orthopneumovirus_NC_038235_1
  - Human_papillomavirus_16
  - human_papillomavirus_18
  - human_papillomavirus_30
  - Human_papillomavirus_type_53
  - Human_papillomavirus_type_6b
  - Human_parechovirus_1
  - Human_parvovirus_B19
  - Human_respiratory_syncytial_virus_A
  - Human_respirovirus_1
  - Human_respirovirus_3_Guangzhou
  - Human_respirovirus_3_NC_001796_2
  - Human_rhinovirus_NAT001
  - Human_T_cell_leukemia_virus_type_I
  - Infectious_bronchitis_virus_Beaudette
  - Infectious_bronchitis_virus_Ind_TN92_03
  - Infectious_bursal_disease_virus_1977_from_Schobries_et_al_1977_A
  - Infectious_bursal_disease_virus_1977_from_Schobries_et_al_1977_B
  - Infectious_bursal_disease_virus_UK661_A
  - Infectious_bursal_disease_virus_UK661_B
  - Infectious_pancreatic_necrosis_virus_A
  - Infectious_pancreatic_necrosis_virus_B
  - Influenza_A_virus_A_California_07_2009_H1N1_1
  - Influenza_A_virus_A_California_07_2009_H1N1_2
  - Influenza_A_virus_A_California_07_2009_H1N1_3
  - Influenza_A_virus_A_California_07_2009_H1N1_4
  - Influenza_A_virus_A_California_07_2009_H1N1_5
  - Influenza_A_virus_A_California_07_2009_H1N1_6
  - Influenza_A_virus_A_California_07_2009_H1N1_7
  - Influenza_A_virus_A_California_07_2009_H1N1_8
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_1
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_2
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_3
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_4
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_5
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_6
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_7
  - Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_8
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_1
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_2
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_3
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_4
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_5
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_6
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_7
  - Influenza_A_virus_A_Hong_Kong_1073_99_H9N2_8
  - Influenza_A_virus_A_Korea_426_1968_H2N2_1
  - Influenza_A_virus_A_Korea_426_1968_H2N2_2
  - Influenza_A_virus_A_Korea_426_1968_H2N2_3
  - Influenza_A_virus_A_Korea_426_1968_H2N2_4
  - Influenza_A_virus_A_Korea_426_1968_H2N2_5
  - Influenza_A_virus_A_Korea_426_1968_H2N2_6
  - Influenza_A_virus_A_Korea_426_1968_H2N2_7
  - Influenza_A_virus_A_Korea_426_1968_H2N2_8
  - Influenza_A_virus_A_New_York_392_2004_H3N2_1
  - Influenza_A_virus_A_New_York_392_2004_H3N2_2
  - Influenza_A_virus_A_New_York_392_2004_H3N2_3
  - Influenza_A_virus_A_New_York_392_2004_H3N2_4
  - Influenza_A_virus_A_New_York_392_2004_H3N2_5
  - Influenza_A_virus_A_New_York_392_2004_H3N2_6
  - Influenza_A_virus_A_New_York_392_2004_H3N2_7
  - Influenza_A_virus_A_New_York_392_2004_H3N2_8
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_1
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_2
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_3
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_4
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_5
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_6
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_7
  - Influenza_A_virus_A_Puerto_Rico_8_1934_H1N1_8
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_1
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_2
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_3
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_4
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_5
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_6
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_7
  - Influenza_A_virus_A_Shanghai_02_2013_H7N9_8
  - Influenza_B_virus_B_Lee_1940_1
  - Influenza_B_virus_B_Lee_1940_2
  - Influenza_B_virus_B_Lee_1940_3
  - Influenza_B_virus_B_Lee_1940_4
  - Influenza_B_virus_B_Lee_1940_5
  - Influenza_B_virus_B_Lee_1940_6
  - Influenza_B_virus_B_Lee_1940_7
  - Influenza_B_virus_B_Lee_1940_8
  - Influenza_C_virus_C_Ann_Arbor_1_50_1
  - Influenza_C_virus_C_Ann_Arbor_1_50_2
  - Influenza_C_virus_C_Ann_Arbor_1_50_3
  - Influenza_C_virus_C_Ann_Arbor_1_50_4
  - Influenza_C_virus_C_Ann_Arbor_1_50_5
  - Influenza_C_virus_C_Ann_Arbor_1_50_6
  - Influenza_C_virus_C_Ann_Arbor_1_50_7
  - Influenza_D_virus_D_swine_Oklahoma_1334_2011_1
  - Influenza_D_virus_D_swine_Oklahoma_1334_2011_2
  - Influenza_D_virus_D_swine_Oklahoma_1334_2011_3
  - Influenza_D_virus_D_swine_Oklahoma_1334_2011_4
  - Influenza_D_virus_D_swine_Oklahoma_1334_2011_5
  - Influenza_D_virus_D_swine_Oklahoma_1334_2011_6
  - Influenza_D_virus_D_swine_Oklahoma_1334_2011_7
  - Isavirus_salaris_3
  - Isavirus_salaris_4
  - Isavirus_salaris_5
  - Isavirus_salaris_6
  - Japanese_encephalitis_virus
  - JC_polyomavirus
  - Lelystad_virus
  - Lumpy_skin_disease_virus_NI_2490
  - Lyssavirus_rabies
  - Maize_streak_virus_A_Ama
  - Maize_streak_virus_A_South_Africa
  - Mamastrovirus_1
  - Mammalian_orthoreovirus_3_Dearing_L1
  - Mammalian_orthoreovirus_3_Dearing_L2
  - Mammalian_orthoreovirus_3_Dearing_L3
  - Mammalian_orthoreovirus_3_Dearing_M1
  - Mammalian_orthoreovirus_3_Dearing_M2
  - Mammalian_orthoreovirus_3_Dearing_M3
  - Mammalian_orthoreovirus_3_Dearing_S1
  - Mammalian_orthoreovirus_3_Dearing_S2
  - Mammalian_orthoreovirus_3_Dearing_S3
  - Mammalian_orthoreovirus_3_Dearing_S4
  - Mammalian_orthoreovirus_3_L1
  - Mammalian_orthoreovirus_3_L2
  - Mammalian_orthoreovirus_3_L3
  - Mammalian_orthoreovirus_3_M1
  - Mammalian_orthoreovirus_3_M2
  - Mammalian_orthoreovirus_3_M3
  - Mammalian_orthoreovirus_3_S1
  - Mammalian_orthoreovirus_3_S2
  - Mammalian_orthoreovirus_3_S3
  - Mammalian_orthoreovirus_3_S4
  - Mammarenavirus_lassaense_L
  - Measles_morbillivirus
  - Middle_East_respiratory_syndrome_related_coronavirus
  - Mogiana_tick_virus_MGTV_V4_11_1
  - Mogiana_tick_virus_MGTV_V4_11_2
  - Mogiana_tick_virus_MGTV_V4_11_3
  - Mogiana_tick_virus_MGTV_V4_11_4
  - Mogiana_tick_virus_SY84_1
  - Mogiana_tick_virus_SY84_2
  - Mogiana_tick_virus_SY84_3
  - Mogiana_tick_virus_SY84_4
  - Monkeypox_virus_Ia
  - Monkeypox_virus_IIb
  - Mumps_orthorubulavirus
  - Norovirus_GI_Hu_BD_2011_GI_7_PNA2_Dhaka1882
  - Norovirus_GI_Hu_JP_1998_GI_6_PNA4_No20_Saitama_98_17
  - Norovirus_GI_Hu_JP_2007_GI_P3_GI_3_Shimizu_KK2866
  - Norovirus_GII_17
  - Norovirus_GII_2
  - Norovirus_GII_Hu_JP_2007_GII_P15_GII_15_Sapporo_HK299
  - Norovirus_GII_Hu_JP_2011_GII_Yuzawa_Gira2HS
  - Norovirus_GII_NORO_176_1_17_12_2015
  - Norovirus_GII_NORO_226_06_01_2016
  - Norovirus_GV
  - Norwalk_like_virus
  - Orbivirus_alphaequi_1
  - Orbivirus_alphaequi_10
  - Orbivirus_alphaequi_3
  - Orbivirus_alphaequi_4
  - Orbivirus_alphaequi_5
  - Orbivirus_alphaequi_7
  - Orbivirus_alphaequi_8
  - Oropouche_virus_L
  - Oropouche_virus_M
  - Oropouche_virus_S
  - Orthohantavirus_hantanense_L
  - Orthohantavirus_hantanense_NC_005218_1
  - Orthohantavirus_hantanense_NC_005219_1
  - Orthohantavirus_seoulense_L
  - Orthohantavirus_seoulense_M
  - Orthohantavirus_seoulense_S
  - Orthonairovirus_haemorrhagiae_L
  - Orthonairovirus_haemorrhagiae_M
  - Orthonairovirus_haemorrhagiae_S
  - Orthopoxvirus_vaccinia
  - Orthotospovirus_tomatomaculae_L
  - Orthotospovirus_tomatomaculae_M
  - Orthotospovirus_tomatomaculae_S
  - Papaya_ringspot_virus
  - Parechovirus_A
  - Paslahepevirus_balayani_NC_074955_1
  - Peach_latent_mosaic_viroid
  - Pepino_mosaic_virus
  - Peste_des_petits_ruminants_virus
  - Piscine_orthoreovirus_L1
  - Piscine_orthoreovirus_L2
  - Piscine_orthoreovirus_L3
  - Piscine_orthoreovirus_M1
  - Piscine_orthoreovirus_M2
  - Piscine_orthoreovirus_M3
  - Piscine_orthoreovirus_S1
  - Piscine_orthoreovirus_S2
  - Piscine_orthoreovirus_S3
  - Piscine_orthoreovirus_S4
  - Plum_pox_virus
  - Porcine_circovirus_2_AUT1
  - Porcine_circovirus_2_JX0301
  - Porcine_circovirus_3
  - Porcine_epidemic_diarrhea_virus
  - Porcine_kobuvirus
  - Porcine_kobuvirus_SH_W_CHN_2010_China
  - Porcine_kobuvirus_swine_S_1_HUN_2007_Hungary
  - Porcine_reproductive_and_respiratory_syndrome_virus
  - Porcine_reproductive_and_respiratory_syndrome_virus_2
  - Potato_spindle_tuber_viroid
  - Potato_virus_Y
  - Primate_norovirus
  - Primate_T_lymphotropic_virus_1
  - Rabbit_hemorrhagic_disease_virus
  - rhinovirus_A1
  - rhinovirus_B14
  - rhinovirus_B3
  - Rice_black_streaked_dwarf_virus_1
  - Rice_black_streaked_dwarf_virus_10
  - Rice_black_streaked_dwarf_virus_5
  - Rice_black_streaked_dwarf_virus_8
  - Rice_yellow_mottle_virus
  - Rift_Valley_fever_virus_L
  - Rift_Valley_fever_virus_M
  - Rift_Valley_fever_virus_S
  - Rotavirus_A_1
  - Rotavirus_A_10
  - Rotavirus_A_11
  - Rotavirus_A_2
  - Rotavirus_A_3
  - Rotavirus_A_4
  - Rotavirus_A_6
  - Rotavirus_A_7
  - Rotavirus_A_8
  - Rotavirus_A_9
  - Rotavirus_C_1
  - Rotavirus_C_2
  - Rotavirus_C_4
  - Rotavirus_C_5
  - Rotavirus_C_6
  - Rotavirus_C_8
  - Rotavirus_C_9
  - Rubella_virus_F_Therien
  - Rubella_virus_RVi_Bismarck_ND_USA_23_08_2B
  - Sapovirus_C12
  - Sapovirus_Hu_Dresden_pJG_Sap01_DE
  - Sapovirus_Hu_GI_Sapporo_MT_2010_1982
  - Sapovirus_Mc10
  - Severe_fever_with_thrombocytopenia_syndrome_virus_L
  - Severe_fever_with_thrombocytopenia_syndrome_virus_M
  - Severe_fever_with_thrombocytopenia_syndrome_virus_S
  - SFTS_virus_HB29_L
  - SFTS_virus_HB29_M
  - SFTS_virus_HB29_S
  - Simian_adenovirus_21
  - Simian_adenovirus_25
  - Simian_Agent_10
  - Sugarcane_mosaic_virus
  - Suid_alphaherpesvirus_1_Composite_of_6_strains
  - Suid_alphaherpesvirus_1_Kaplan
  - Swine_enteric_coronavirus
  - Tick_borne_encephalitis_virus
  - Tomato_leaf_curl_New_Delhi_virus_DNA_A
  - Tomato_yellow_leaf_curl_virus
  - Torque_teno_virus_TTV_HD14a_gbDhDi33_32
  - Transmissible_gastroenteritis_virus
  - Trichovirus_mali
  - Turkey_coronavirus
  - Turnip_mosaic_virus
  - Usutu_virus
  - Varroa_destructor_virus_1
  - Viral_hemorrhagic_septicemia_virus_Fil3
  - Watermelon_mosaic_virus
  - West_Nile_virus_385_99
  - West_Nile_virus_956
  - Yellow_fever_virus
  - Zaire_ebolavirus
  - Zika_virus_MR_766
  - Zika_virus_Natal_RGN
  - Zucchini_yellow_mosaic_virus
